import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import dotenv
from main import generate_report_payload, generate_commentary
from saveimg import get_weather_count

dotenv.load_dotenv()




def send_report_email():
    """
    Generates the natural gas report and sends it via email with an HTML table.
    """
    sender_email = os.getenv("EMAIL_USER")
    receiver_email = "vihansrathore2006@gmail.com"
    password = os.getenv("EMAIL_PASSWORD")

    if not sender_email or not password:
        print("Error: EMAIL_USER or EMAIL_PASSWORD not configured.")
        return

    print("Fetching market data and metrics...")
    payload = generate_report_payload()
    metrics = payload.get("storage_model_evaluation", {})

    trade_bias = metrics.get('trade_bias', 'Neutral')
    color = "#2ecc71" if "Bull" in str(trade_bias) else "#e74c3c" if "Bear" in str(trade_bias) else "#7f8c8d"

    print("Generating AI commentary...")
    commentary = generate_commentary()

    print(f"Preparing email for {receiver_email}...")
    
    msg = MIMEMultipart()
    msg['From'] = f"Nat-Gas AI <{sender_email}>"
    msg['To'] = receiver_email
    msg['Subject'] = f"NG Market Intelligence: {trade_bias.upper()}"

    # Process commentary for HTML
    html_commentary = commentary.replace("\n", "<br>")
    
    html_content = f"""
    <html>
    <body style="margin: 0; padding: 20px; background-color: #f4f7f6; font-family: 'Segoe UI', Arial, sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
            <h1 style="color: {color}; margin-top: 0; font-size: 28px; border-bottom: 2px solid #eee; padding-bottom: 15px; text-align: center;">
                {trade_bias.upper()}
            </h1>
            <div style="line-height: 1.8; color: #444; font-size: 16px; margin-top: 25px;">
                {html_commentary}
            </div>
            <div style="text-align: center; color: #95a5a6; font-size: 12px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 15px;">
                Generated by Nat-Gas AI Predictor Engine<br>
                {payload.get('report_metadata', {}).get('generated_at', '')}
            </div>
        </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    send_report_email()