import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import dotenv
from main import generate_report_payload, generate_commentary
from saveimg import get_weather_count

dotenv.load_dotenv()



def create_html_table(metrics, weather_7d):
    """
    Creates a minimalistic HTML table for the market metrics.
    """
    labels = {
        "actual_change_bcf": "Actual Change (Bcf)",
        "expected_change_bcf": "Expected Change (Bcf)",
        "weekly_deviation_bcf": "Weekly Deviation (Bcf)",
        "trade_bias": "Trade Bias"
    }
    
    table_rows = ""
    for key, label in labels.items():
        val = metrics.get(key, "N/A")
        # Apply conditional coloring for Trade Bias
        style = ""
        if key == "trade_bias":
            color = "#2ecc71" if "Bull" in str(val) else "#e74c3c" if "Bear" in str(val) else "#34495e"
            style = f' style="color: {color}; font-weight: bold;"'
        
        table_rows += f"""
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 10px; color: #7f8c8d;">{label}</td>
            <td style="padding: 10px; color: #2c3e50; text-align: right;"{style}>{val}</td>
        </tr>"""

    # Add Weather Row
    table_rows += f"""
    <tr style="border-bottom: 1px solid #eee;">
        <td style="padding: 10px; color: #7f8c8d;">Temp Forecast (7-day)</td>
        <td style="padding: 10px; color: #2c3e50; text-align: right; font-style: italic;">{weather_7d}</td>
    </tr>"""

    return f"""
    <div style="max-width: 800px; margin: 20px auto; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #2c3e50; color: white; padding: 20px; text-align: center;">
            <h2 style="margin: 0; font-weight: 300;">Natural Gas Analytical Metrics</h2>
        </div>
        <table style="width: 100%; border-collapse: collapse; background-color: white;">
            {table_rows}
        </table>
    </div>"""

def send_report_email():
    """
    Generates the natural gas report and sends it via email with an HTML table.
    """
    sender_email = os.getenv("EMAIL_USER")
    receiver_email = "vihansrathore2006@gmail.com"
    password = os.getenv("EMAIL_PASSWORD")

    if not sender_email or not password:
        print("Error: EMAIL_USER or EMAIL_PASSWORD not configured.")
        return

    print("Fetching market data and metrics...")
    payload = generate_report_payload()
    metrics = payload.get("storage_model_evaluation", {})

    print("Fetching weather forecast...")
    weather_data = get_weather_count()
    weather_7d = weather_data[2] if weather_data else "Data not available"

    print("Generating AI commentary...")
    commentary = generate_commentary()

    print(f"Preparing email for {receiver_email}...")
    
    msg = MIMEMultipart()
    msg['From'] = f"Nat-Gas AI <{sender_email}>"
    msg['To'] = receiver_email
    msg['Subject'] = f"NG Market Intelligence: {metrics.get('trade_bias', 'Update')}"

    # Build HTML Content
    metrics_table = create_html_table(metrics, weather_7d)
    
    # Process commentary for HTML (simple newline to break)
    html_commentary = commentary.replace("\n", "<br>")
    
    html_content = f"""
    <html>
    <body style="margin: 0; padding: 0; background-color: #f9f9f9; font-family: 'Segoe UI', Arial, sans-serif;">
        <div style="padding: 20px;">
            {metrics_table}
            
            <div style="max-width: 800px; margin: 20px auto; background-color: white; padding: 30px; border-radius: 8px; border: 1px solid #ddd;">
                <h3 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 0;">Natural Gas for Today</h3>
                <div style="line-height: 1.6; color: #34495e; font-size: 15px;">
                    {html_commentary}
                </div>
            </div>
            
            <div style="text-align: center; color: #95a5a6; font-size: 12px; margin-top: 20px;">
                Generated by Nat-Gas AI Predictor Engine<br>
                {payload.get('report_metadata', {}).get('generated_at', '')}
            </div>
        </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(html_content, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

def msg():
    from twilio.rest import Client
    from ng_signal import data, strat
    from datetime import datetime

    sid, token = os.getenv("TWILIO_ACCOUNT_SID"), os.getenv("TWILIO_AUTH_TOKEN")

    print("Checking technical signals for Natural Gas...")
    try:
        # Get latest signal
        df_data = data('NG=F')
        signals = strat(df_data)
        
        active_signal = None
        if signals['buy_1']: active_signal = "STRONGLY BUY"
        elif signals['sell_1']: active_signal = "STRONGLY SELL"
        elif signals['buy_0.5']: active_signal = "MODERATELY BUY"
        elif signals['sell_0.5']: active_signal = "MODERATELY SELL"

        if not active_signal:
            print("No actionable signal detected in ng_signal.py logic.")
            return

        print(f"Signal detected: {active_signal}. Sending WhatsApp notification...")

        client = Client(sid, token)

        # Get current time for the message
        now = datetime.now().strftime("%H:%M")
        today = datetime.now().strftime("%d/%m")

        message = client.messages.create(
            from_='whatsapp:+14155238886',
            content_sid='HXb5b62575e6e4ff6129ad7c8efe1f983e',
            content_variables=f'{{"1":"{active_signal}","2":"{now} on {today}"}}',
            to='whatsapp:+917828374376'
        )

        print(f"Message sent successfully! SID: {message.sid}")
    except Exception as e:
        print(f"Error in msg() notification logic: {e}")

if __name__ == "__main__":
    msg()